# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_trade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custos_e_Despesas',
        ),
        migrations.DeleteModel(
            name='HorasOperando',
        ),
        migrations.RenameField(
            model_name='operacoes',
            old_name='comentarios_adiocionais',
            new_name='comentarios_adicionais',
        ),
    ]
