# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_day_trade', '0003_operacoes_corretora'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='setup_de_entrada',
            field=models.CharField(default='H/L2', max_length=30, verbose_name='Setup de entrada*:'),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='estrategia',
            field=models.CharField(choices=[('Momentum Context', 'Momentum Context'), ('Trend Context', 'Trend Context'), ('Range Context', 'Range Context'), ('Reversal Context', 'Reversal Context')], default='Momentum Context', max_length=30),
        ),
    ]
