# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_day_trade', '0004_auto_20191128_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='contexto',
            field=models.CharField(blank=True, choices=[('Momentum Context', 'Momentum Context'), ('Trend Context', 'Trend Context'), ('Range Context', 'Range Context')], default='Momentum Context', max_length=30),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='estrategia',
            field=models.CharField(choices=[('Bear/Bull Flag', 'Bear/Bull Flag'), ('First PB at Anti', 'First PB at Anti'), ('Double Top/Bottom', 'Double Top/Bottom')], default='Bear/Bull Flag', max_length=30),
        ),
    ]
