# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-01 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_day_trade', '0005_auto_20191128_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacoes',
            name='contexto',
        ),
        migrations.RemoveField(
            model_name='operacoes',
            name='setup_de_entrada',
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='estrategia',
            field=models.CharField(default='H/L2', max_length=30, verbose_name='Estrat\xe9gia*:'),
        ),
    ]
