# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_day_trade', '0006_auto_20191130_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='nivel_volume',
            field=models.CharField(blank=True, choices=[('Alto', 'Alto'), ('Baixo', 'Baixo')], max_length=50, verbose_name='N\xedvel de Volume:'),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='estrategia',
            field=models.CharField(default='Two Legged Pullback', max_length=30, verbose_name='Estrat\xe9gia*:'),
        ),
    ]
