# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_day_trade', '0007_auto_20191206_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacoes',
            name='nivel_volume',
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='estrategia',
            field=models.CharField(choices=[('Two Legged Pullback', 'Two Legged Pullback'), ('Trap Against Bias', 'Trap Against Bias'), ('H/L2', 'H/L2')], default='Two Legged Pullback', max_length=30, verbose_name='Estrat\xe9gia*:'),
        ),
    ]
