# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-15 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_day_trade', '0008_auto_20191207_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='contexto',
            field=models.CharField(blank=True, choices=[('Momentum', 'Momentum'), ('Tend\xeancia', 'Tend\xeancia'), ('Consolida\xe7\xe3o', 'Conslida\xe7\xe3o')], default='Momentum', max_length=100, verbose_name='Contexto:'),
        ),
        migrations.AddField(
            model_name='operacoes',
            name='distancia_media',
            field=models.CharField(blank=True, choices=[('Testando MM21', 'Testando MM21'), ('Entre a MM21 e BK', 'Entre a MM21 e BK'), ('Longe da MM21', 'Longe da MM21'), ('Testando BK', 'Testando BK'), ('Acima/Abaixo da MM21', 'Acima/Abaixo ou Acima da MM21')], default='Testando MM21', max_length=100, verbose_name='Distancia da m\xe9dia:'),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='estrategia',
            field=models.CharField(choices=[('H/L2', 'H/L2'), ('Falha de H/L2', 'Falha de H/L2'), ('Nested Pullback', 'Nested Pullback')], default='H/L2', max_length=30, verbose_name='Estrat\xe9gia*:'),
        ),
    ]
