# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aporte', models.DateField(blank=True, null=True, verbose_name='Data do aporte:')),
                ('aportes', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor do aporte:')),
            ],
            options={
                'verbose_name_plural': 'Aportes',
            },
        ),
        migrations.CreateModel(
            name='Operacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data de abertura:')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data de fechamento:')),
                ('vencimento_das_opcoes', models.DateField(blank=True, null=True, verbose_name='Data de vencimento das op\xe7\xf5es:')),
                ('nivel_vol_implicita', models.DecimalField(blank=True, decimal_places=1, max_digits=50, null=True, verbose_name='N\xedvel de Vol. Implicita na data:')),
                ('serie_vencimento_opcoes', models.CharField(blank=True, choices=[('Janeiro - A/M', 'Janeiro - A/M'), ('Fevereiro - B/N', 'Fevereiro B/N'), ('Mar\xe7o - C/O', 'Mar\xe7o - C/O'), ('Abril - D/P', 'Abril - D/P'), ('Maio - E/Q', 'Maio - E/Q'), ('Junho - F/R', 'Junho - F/R'), ('Julho - G/S', 'Julho - G/S'), ('Agosto - H/T', 'Agosto H/T'), ('Setembro - I/U', 'Setembro I/U'), ('Outubro - J/V', 'Outubro - J/V'), ('Novembro - K/W', 'Novembro - K/W'), ('Dezembro - L/X', 'Dezembro - L/X')], max_length=50, verbose_name='Serie de vencimento das op\xe7\xf5es:')),
                ('ticker_ativo_subjacente', models.CharField(blank=True, default='PETR4', max_length=30, verbose_name='Ticker do ativo subjacente:')),
                ('motivo_da_operacao', models.CharField(blank=True, max_length=50, verbose_name='Motivo da opera\xe7\xe3o:')),
                ('timeframe_do_grafico', models.CharField(blank=True, choices=[('Di\xe1rio', 'Di\xe1rio'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], default='Di\xe1rio', max_length=30, verbose_name='TimeFrame do gr\xe1fico utililizado:')),
                ('imagem_entrada', models.ImageField(blank=True, upload_to=b'', verbose_name='Imagem da entrada no gr\xe1fico:')),
                ('estrategia_de_alta', models.CharField(blank=True, choices=[('Long Call', 'Long Call'), ('Bull Call Spread', 'Bull Call Spread'), ('Short Put', 'Short Put'), ('Long Put Spread', 'Long Put Spread'), ('Covered Call', 'Covered Call'), ('Covered Strangle', 'Covered Strangle'), ('Married (Protective) Put', 'Married (Protective) Put'), ('The Collar', 'The Collar'), ('Synthetic Long Stock', 'Synthetic Long Stock')], max_length=50, verbose_name='Estrat\xe9gia de alta utilizada:')),
                ('estrategia_de_baixa', models.CharField(blank=True, choices=[('Long Put', 'Long Put'), ('Short Put Spread', 'Short Put Spread'), ('Short Call', 'Short Call'), ('Short Iron Butterflies', 'Short Iron Butterflies'), ('Covered Put', 'Covered Put'), ('Synthetic Long Stock', 'Synthetic Long Stock')], max_length=50, verbose_name='Estrat\xe9gia de baixa utilizada:')),
                ('estrategia_de_lateralidade', models.CharField(blank=True, choices=[('Short Strangle', 'Short Strangle'), ('Short Straddle', 'Short Straddle'), ('Short Iron Condor', 'Short Iron Condor'), ('Short Iron Butterfly', 'Short Iron Butterfly'), ('Long Butterfly', 'Long Butterfly'), ('Long Condor', 'Long Condor'), ('Short Condor', 'Short Condor'), ('Long Strangle', 'Long Strangle'), ('Long Straddle', 'Long Straddle'), ('Long Iron Condor', 'Long Iron Condor'), ('Long Iron Butterfly', 'Long Iron Butterfly')], max_length=50, verbose_name='Estrat\xe9gia de lateralidade utilizada:')),
                ('contratos', models.IntegerField(blank=True, null=True, verbose_name='N. de contratos:')),
                ('premiooucusto_da_operacao', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Premio/Custo da opera\xe7\xe3o')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Resultado da Op.:')),
                ('comentarios', models.TextField(blank=True, verbose_name='Coment\xe1rios:')),
                ('imagem_saida_grafico', models.ImageField(blank=True, upload_to=b'', verbose_name='Imagem da sa\xedda no gr\xe1fico:')),
            ],
            options={
                'verbose_name_plural': 'Opera\xe7\xf5es',
            },
        ),
    ]
