# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-22 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aportes',
        ),
        migrations.RemoveField(
            model_name='operacoes',
            name='imagem_entrada',
        ),
        migrations.RemoveField(
            model_name='operacoes',
            name='imagem_saida_grafico',
        ),
    ]
