# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aporte', models.DateField(blank=True, null=True, verbose_name='Data do aporte:')),
                ('aportes', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor do aporte:')),
            ],
            options={
                'verbose_name_plural': 'Aportes',
            },
        ),
    ]
